### ISSUE TITLE
OSError: This script is intended to run on a Raspberry Pi.

### ISSUE THREAD

**Issue by garethiowc** [yeutterg/speech-to-speech-smart-speaker#2]
Hi, 

I've followed the install steps on my Pi4 but i'm getting this error - 

`gareth@PIssistannt:~/speech-to-speech-smart-speaker $ python3 main.py
pygame 2.6.1 (SDL 2.28.4, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
[INIT] Platform Info: uname_result(system='Linux', node='PIssistannt', release='6.6.62+rpt-rpi-v8', version='#1 SMP PREEMPT Debian 1:6.6.6                                                         2-1+rpt1 (2024-11-25)', machine='aarch64')
Traceback (most recent call last):
  File "/home/gareth/speech-to-speech-smart-speaker/main.py", line 35, in <module>
    main()
  File "/home/gareth/speech-to-speech-smart-speaker/main.py", line 15, in main
    hardware_interface = HardwareInterface(speech_handler)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/speech-to-speech-smart-speaker/hardware.py", line 142, in __init__
    raise EnvironmentError("This script is intended to run on a Raspberry Pi.")
OSError: This script is intended to run on a Raspberry Pi.
`

Same error if i run from ssh window or directly on the pi using hdmi and keyboard

Thanks 
Gareth

**Comment by yeutterg** [comment]
Hi Gareth, thanks for letting me know. Pretty sure this has to do with the difference in how GPIOs are handled between the Pi 4 and Pi 5. I think we might need to have a different configuration depending on the base system.

Also, stay tuned because I am working on the LiveKit implementation now. Some things may change in the codebase which might require a reinstall, FYI.

**Comment by garethiowc** [comment]
Hi Greg,I managed to get it working by commenting out the check. Everything appears to be working as I see the simulated text on the screen, button press, led and beep from the speaker is heard.Super excited to try the working realtime integration and your other new features. ThanksGareth Sent from my iPhoneOn 11 Dec 2024, at 2:48 am, Greg Yeutter ***@***.***> wrote:﻿
Hi Gareth, thanks for letting me know. Pretty sure this has to do with the difference in how GPIOs are handled between the Pi 4 and Pi 5. I think we might need to have a different configuration depending on the base system.
Also, stay tuned because I am working on the LiveKit implementation now. Some things may change in the codebase which might require a reinstall, FYI.

**Comment by yeutterg** [comment]
Great to know, thanks Gareth! Will be sure to take this check into account for future releases.
